<built-in method with_traceback of TypeError object at 0x03961ED8>